pipeline {
    agent {
        kubernetes {
            label 'my-pod-template'
            defaultContainer 'curl'
            yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
  - name: curl
    image: centos:latest
    command:
    - cat
    tty: true
  - name: busybox
    image: busybox
    command:
    - cat
    tty: true
"""
        }
    }
  stages{
    stage('api call'){
      environment {
        FLOWSERVER = credentials('flow-server-url')
      }
      steps{
        withCredentials([usernamePassword(credentialsId: 'flow-admin-creds', passwordVariable: 'vPassword', usernameVariable: 'vUser')]) {
          //sh 'curl -u $vPassword:$vUser --insecure -X GET "${FLOWSERVER}/rest/v1.0/users" -H "accept: application/json"'
          sh  'curl -s -u $vPassword:$vUser --insecure -X GET "https://ps9.ecloud-kdemo.com/rest/v1.0/jobs/283e07fa-598f-11e9-b750-02422b598c05" -H "accept: application/json" |jq .job.combinedStatus.status  '       
         
            
        }   
      }
    }
  }
}
