pipeline{
    agent any
    parameters{
        choice(choices: ['dev', 'prd', 'ist'], description: 'What environment ?', name: 'envtarget')
        string(defaultValue: "MyCompoenent", description: 'Component Name ?', name: 'component')
    }
    stages{
        stage('check'){
            steps{
            echo "${params.envtarget}"
        
            }
        }
        stage('call proceedure'){
            
            
            steps{
               step(
                   shell(
                       ([$class: 'ElectricFlowRunProcedure',
                      configuration: 'flow',
                      projectName : 'Training_sbrown',
                      procedureName : 'SimpleProceedureTest',
                      procedureParameters : """{"procedure":{"procedureName":"SimpleProceedureTest","parameters":[{"actualParameterName":"arg1","value":"${params.envtarget}"}]}}"""
                ])
                )
                )
            }
        }
        //stage('get-status'){
        //    steps{
        //        sh "curl -u sbrown:sbrown  https://ps9.ecloud-kdemo.com/rest/v1.0/jobs/7f30941b-b74f-11e9-a8ba-02425352dfc1 
         //       //|/data/jq '.job.status'"
          //  }        
        //}
        
    }
}
